name: Build and push derper Docker image

on:
  workflow_dispatch:
  schedule:
    - cron: "11 0 * * *"

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  pages: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-latest-tag:
    name: Get latest tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout derper
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: tailscale/tailscale
      - name: Get derper latest tag
        id: tag
        run: echo "tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Get my latest tag
        id: mytag
        run: echo "mytag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> "$GITHUB_OUTPUT"
      - name: Add tag
        id: addtag
        if: steps.tag.outputs.tag != steps.mytag.outputs.mytag
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag ${{ steps.tag.outputs.tag }}
          git push origin --tags
          echo "addtag=true" >> "$GITHUB_OUTPUT"

    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      addtag: ${{ steps.addtag.outputs.addtag }}

  build-docker-image:
    needs: get-latest-tag
    if: needs.get-latest-tag.outputs.addtag == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: clone tailscale
        run: |
          mkdir build_src
          git clone https://github.com/tailscale/tailscale build_src/tailscale

      - name: modify
        run: |
          sed -i '/hi.ServerName != m.hostname/,+2d' build_src/tailscale/cmd/derper/cert.go
          sed -i 's|This is a <a href="https://tailscale.com/">Tailscale</a> DERP server.|这是一个自用的 <a href="https://tailscale.com/">Tailscale</a> DERP 中继服务器。|g' build_src/tailscale/cmd/derper/derper.go
          sed -i 's|It provides STUN, interactive connectivity establishment, and relaying of end-to-end encrypted traffic|为 Tailscale 客户端提供 STUN、ICE 协商和端到端加密流量中继服务。|g' build_src/tailscale/cmd/derper/derper.go
          sed -i 's|for Tailscale clients.||g' build_src/tailscale/cmd/derper/derper.go
          sed -i 's|If you suspect abuse, please contact <a href="mailto:security@tailscale.com">security@tailscale.com</a>.|如有问题请联系管理员。|g' build_src/tailscale/cmd/derper/derper.go
          sed -i 's|Tailscale Security Policies|安全策略|g' build_src/tailscale/cmd/derper/derper.go
          sed -i 's|Tailscale Acceptable Use Policies|使用条款|g' build_src/tailscale/cmd/derper/derper.go
          sed -i 's|About DERP|DERP 说明|g' build_src/tailscale/cmd/derper/derper.go
          sed -i 's|Protocol &amp; Go docs|协议文档|g' build_src/tailscale/cmd/derper/derper.go
          sed -i 's|How to run a DERP server|部署指南|g' build_src/tailscale/cmd/derper/derper.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #- name: Get tag
      #  id: tag
      #  uses: devops-actions/action-get-tag@v1.0.1
      #  with:
      #    strip_v: true # Optional: Remove 'v' character from version

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.actor }}/derper
          tags: |
            type=ref,event=tag
            type=raw,value=${{ needs.get-latest-tag.outputs.tag }}

      - name: Build and push Docker images to ghcr.io
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
